### ISSUE TITLE
Patching process removing LAA flag

### ISSUE THREAD

**Issue by JavidPack** [RomSteady/RomTerraria#2]
Terraria has been setting the Large Address Aware flag in recent releases, but I noticed the RomTerraria patched versions do not have it set. (I noticed this because I've received messages regarding my tModLoader mod LargeWorldEnabler throwing OutOfMemory errors when users of RomTerraria patch tModLoader) I don't really understand the patching process, but here is another Terraria patching program who fixed the issue, hopefully you can integrate similar code:
https://github.com/dougbenham/TerrariaPatcher/commit/ca332bbb04d576f641d6c8de70c65f4eb84ddb61

To check the LAA flag, run "dumpbin /headers Terraria.exe | more" (You might need to execute this command from the "VS2015 x64 native tools command prompt")  and you should see "Application can handle large (>2GB) addresses" right above "32 bit word machine" on the first page. With the RomTerraria patched version, no such message is shown.

![cmd_2016-12-19_08-22-52](https://cloud.githubusercontent.com/assets/4522492/21317920/639283dc-c5c4-11e6-92ed-9197368b1b77.png)

**Comment by RomSteady** [comment]
Thank you for the investigation and the patch.  I'll look into seeing if I can correct this tonight.

**Comment by RomSteady** [comment]
I have added in the MakeLargeAddressAware code and provided credit in the readme.  I'm currently trying to fix a render issue with the water in 1.3.4.4 before committing the fix.

**Comment by RomSteady** [comment]
Fixed in the most recent release.
