### ISSUE TITLE
Download links are broken

### ISSUE THREAD

**Issue by Tronnic** [RomSteady/RomTerraria#3]
Hello, I used to play terraria on my 3440x1440 screen a few years ago. I'd like to play it again but the download links on your blog do not work anymore and I don't know how to compile this github code. Is there any chance you can reupload it somewhere? Terraria doesn't like my resolution and my game is cut off top and bottom. Thanks a lot for your effort! :)

**Comment by RomSteady** [comment]
I haven't uploaded the 1.3.5.x rewrite for RomTerraria to GitHub yet.  For just unlocking the resolution, you can use RTResolution from this post:

http://romsteady.blogspot.com/2017/06/rtresolution-v02-available-now.html
